const movies = [
  { title: "Vikram", language: "Tamil", genres: ["Action"], poster: null },
  { title: "Thuppakki", language: "Tamil", genres: ["Action"], poster: null },
  { title: "Mersal", language: "Tamil", genres: ["Action"], poster: null },
  { title: "Theri", language: "Tamil", genres: ["Action"], poster: null },
  { title: "Bigil", language: "Tamil", genres: ["Action"], poster: null },
  { title: "Sarkar", language: "Tamil", genres: ["Action"], poster: null },
  { title: "Master", language: "Tamil", genres: ["Action"], poster: null },
  { title: "Darbar", language: "Tamil", genres: ["Action"], poster: null },
  { title: "Kabali", language: "Tamil", genres: ["Action"], poster: null },
  { title: "Petta", language: "Tamil", genres: ["Action"], poster: null },
  { title: "Mad Max: Fury Road", language: "English", genres: ["Action"], poster: null },
  { title: "John Wick", language: "English", genres: ["Action"], poster: null },
  { title: "The Dark Knight", language: "English", genres: ["Action"], poster: null },
  { title: "Gladiator", language: "English", genres: ["Action"], poster: null },
  { title: "Inception", language: "English", genres: ["Action"], poster: null },
  { title: "The Matrix", language: "English", genres: ["Action"], poster: null },
  { title: "Die Hard", language: "English", genres: ["Action"], poster: null },
  { title: "Mission: Impossible - Fallout", language: "English", genres: ["Action"], poster: null },
  { title: "Skyfall", language: "English", genres: ["Action"], poster: null },
  { title: "Terminator 2: Judgment Day", language: "English", genres: ["Action"], poster: null },
  { title: "War", language: "Hindi", genres: ["Action"], poster: null },
  { title: "Pathaan", language: "Hindi", genres: ["Action"], poster: null },
  { title: "Baaghi 3", language: "Hindi", genres: ["Action"], poster: null },
  { title: "Singham", language: "Hindi", genres: ["Action"], poster: null },
  { title: "Ghajini", language: "Hindi", genres: ["Action"], poster: null },
  { title: "Dhoom 3", language: "Hindi", genres: ["Action"], poster: null },
  { title: "Tiger Zinda Hai", language: "Hindi", genres: ["Action"], poster: null },
  { title: "Krrish 3", language: "Hindi", genres: ["Action"], poster: null },
  { title: "Rowdy Rathore", language: "Hindi", genres: ["Action"], poster: null },
  { title: "Wanted", language: "Hindi", genres: ["Action"], poster: null },
  { title: "Baahubali", language: "Telugu", genres: ["Action"], poster: null },
  { title: "RRR", language: "Telugu", genres: ["Action"], poster: null },
  { title: "Pushpa", language: "Telugu", genres: ["Action"], poster: null },
  { title: "Arjun Reddy", language: "Telugu", genres: ["Action"], poster: null },
  { title: "Saaho", language: "Telugu", genres: ["Action"], poster: null },
  { title: "Bharat Ane Nenu", language: "Telugu", genres: ["Action"], poster: null },
  { title: "Sye Raa Narasimha Reddy", language: "Telugu", genres: ["Action"], poster: null },
  { title: "Ala Vaikunthapurramuloo", language: "Telugu", genres: ["Action"], poster: null },
  { title: "Sarileru Neekevvaru", language: "Telugu", genres: ["Action"], poster: null },
  { title: "Vakeel Saab", language: "Telugu", genres: ["Action"], poster: null },
  { title: "Lucifer", language: "Malayalam", genres: ["Action"], poster: null },
  { title: "Ayyappanum Koshiyum", language: "Malayalam", genres: ["Action"], poster: null },
  { title: "Pulimurugan", language: "Malayalam", genres: ["Action"], poster: null },
  { title: "Odiyan", language: "Malayalam", genres: ["Action"], poster: null },
  { title: "Mikhael", language: "Malayalam", genres: ["Action"], poster: null },
  { title: "Kurup", language: "Malayalam", genres: ["Action"], poster: null },
  { title: "Marakkar: Lion of the Arabian Sea", language: "Malayalam", genres: ["Action"], poster: null },
  { title: "The Priest", language: "Malayalam", genres: ["Action"], poster: null },
  { title: "Kammara Sambhavam", language: "Malayalam", genres: ["Action"], poster: null },
  { title: "Villain", language: "Malayalam", genres: ["Action"], poster: null },
  { title: "K.G.F", language: "Kannada", genres: ["Action"], poster: null },
  { title: "Kantara", language: "Kannada", genres: ["Action"], poster: null },
  { title: "Roberrt", language: "Kannada", genres: ["Action"], poster: null },
  { title: "Pogaru", language: "Kannada", genres: ["Action"], poster: null },
  { title: "Avane Srimannarayana", language: "Kannada", genres: ["Action"], poster: null },
  { title: "Yajamana", language: "Kannada", genres: ["Action"], poster: null },
  { title: "The Villain", language: "Kannada", genres: ["Action"], poster: null },
  { title: "Mufti", language: "Kannada", genres: ["Action"], poster: null },
  { title: "Rajaratha", language: "Kannada", genres: ["Action"], poster: null },
  { title: "Kurukshetra", language: "Kannada", genres: ["Action"], poster: null },
  { title: "Ratsasan", language: "Tamil", genres: ["Thriller"], poster: null },
  { title: "Vettaiyaadu Vilaiyaadu", language: "Tamil", genres: ["Thriller"], poster: null },
  { title: "Thani Oruvan", language: "Tamil", genres: ["Thriller"], poster: null },
  { title: "Vikram Vedha", language: "Tamil", genres: ["Thriller"], poster: null },
  { title: "Imaikkaa Nodigal", language: "Tamil", genres: ["Thriller"], poster: null },
  { title: "Dhuruvangal Pathinaaru", language: "Tamil", genres: ["Thriller"], poster: null },
  { title: "Nerkonda Paarvai", language: "Tamil", genres: ["Thriller"], poster: null },
  { title: "Psycho", language: "Tamil", genres: ["Thriller"], poster: null },
  { title: "Visaranai", language: "Tamil", genres: ["Thriller"], poster: null },
  { title: "Por Thozhil", language: "Tamil", genres: ["Thriller"], poster: null },
  { title: "Gone Girl", language: "English", genres: ["Thriller"], poster: null },
  { title: "Se7en", language: "English", genres: ["Thriller"], poster: null },
  { title: "Prisoners", language: "English", genres: ["Thriller"], poster: null },
  { title: "Shutter Island", language: "English", genres: ["Thriller"], poster: null },
  { title: "The Silence of the Lambs", language: "English", genres: ["Thriller"], poster: null },
  { title: "Zodiac", language: "English", genres: ["Thriller"], poster: null },
  { title: "Nightcrawler", language: "English", genres: ["Thriller"], poster: null },
  { title: "Enemy", language: "English", genres: ["Thriller"], poster: null },
  { title: "Oldboy", language: "English", genres: ["Thriller"], poster: null },
  { title: "The Girl with the Dragon Tattoo", language: "English", genres: ["Thriller"], poster: null },
  { title: "Drishyam", language: "Hindi", genres: ["Thriller"], poster: null },
  { title: "Andhadhun", language: "Hindi", genres: ["Thriller"], poster: null },
  { title: "Badla", language: "Hindi", genres: ["Thriller"], poster: null },
  { title: "Talaash", language: "Hindi", genres: ["Thriller"], poster: null },
  { title: "Kahaani", language: "Hindi", genres: ["Thriller"], poster: null },
  { title: "Raman Raghav 2.0", language: "Hindi", genres: ["Thriller"], poster: null },
  { title: "Ittefaq", language: "Hindi", genres: ["Thriller"], poster: null },
  { title: "A Wednesday", language: "Hindi", genres: ["Thriller"], poster: null },
  { title: "Ugly", language: "Hindi", genres: ["Thriller"], poster: null },
  { title: "NH10", language: "Hindi", genres: ["Thriller"], poster: null },
  { title: "Drushyam", language: "Telugu", genres: ["Thriller"], poster: null },
  { title: "HIT: The First Case", language: "Telugu", genres: ["Thriller"], poster: null },
  { title: "Goodachari", language: "Telugu", genres: ["Thriller"], poster: null },
  { title: "Agent Sai Srinivasa Athreya", language: "Telugu", genres: ["Thriller"], poster: null },
  { title: "Rakshasudu", language: "Telugu", genres: ["Thriller"], poster: null },
  { title: "Evaru", language: "Telugu", genres: ["Thriller"], poster: null },
  { title: "Ninnu Kori", language: "Telugu", genres: ["Thriller"], poster: null },
  { title: "Kshanam", language: "Telugu", genres: ["Thriller"], poster: null },
  { title: "118", language: "Telugu", genres: ["Thriller"], poster: null },
  { title: "Antariksham 9000 KMPH", language: "Telugu", genres: ["Thriller"], poster: null },
  { title: "Drishyam", language: "Malayalam", genres: ["Thriller"], poster: null },
  { title: "Memories", language: "Malayalam", genres: ["Thriller"], poster: null },
  { title: "Joseph", language: "Malayalam", genres: ["Thriller"], poster: null },
  { title: "Forensic", language: "Malayalam", genres: ["Thriller"], poster: null },
  { title: "Anjaam Pathiraa", language: "Malayalam", genres: ["Thriller"], poster: null },
  { title: "C U Soon", language: "Malayalam", genres: ["Thriller"], poster: null },
  { title: "Cold Case", language: "Malayalam", genres: ["Thriller"], poster: null },
  { title: "Nayattu", language: "Malayalam", genres: ["Thriller"], poster: null },
  { title: "Operation Java", language: "Malayalam", genres: ["Thriller"], poster: null },
  { title: "Iratta", language: "Malayalam", genres: ["Thriller"], poster: null },
  { title: "Lucia", language: "Kannada", genres: ["Thriller"], poster: null },
  { title: "RangiTaranga", language: "Kannada", genres: ["Thriller"], poster: null },
  { title: "U Turn", language: "Kannada", genres: ["Thriller"], poster: null },
  { title: "Gargaru", language: "Kannada", genres: ["Thriller"], poster: null },
  { title: "Kavaludaari", language: "Kannada", genres: ["Thriller"], poster: null },
  { title: "Bell Bottom", language: "Kannada", genres: ["Thriller"], poster: null },
  { title: "Chambal", language: "Kannada", genres: ["Thriller"], poster: null },
  { title: "Gultoo", language: "Kannada", genres: ["Thriller"], poster: null },
  { title: "Tagaru", language: "Kannada", genres: ["Thriller"], poster: null },
  { title: "Rathnan Prapancha", language: "Kannada", genres: ["Thriller"], poster: null },
  { title: "Pizza", language: "Tamil", genres: ["Horror"], poster: null },
  { title: "Maya", language: "Tamil", genres: ["Horror"], poster: null },
  { title: "Demonte Colony", language: "Tamil", genres: ["Horror"], poster: null },
  { title: "Aval", language: "Tamil", genres: ["Horror"], poster: null },
  { title: "Eeram", language: "Tamil", genres: ["Horror"], poster: null },
  { title: "13B", language: "Tamil", genres: ["Horror"], poster: null },
  { title: "Aranmanai", language: "Tamil", genres: ["Horror"], poster: null },
  { title: "Kanchana", language: "Tamil", genres: ["Horror"], poster: null },
  { title: "Yaamirukka Bayamey", language: "Tamil", genres: ["Horror"], poster: null },
  { title: "Muni", language: "Tamil", genres: ["Horror"], poster: null },
  { title: "The Conjuring", language: "English", genres: ["Horror"], poster: null },
  { title: "Hereditary", language: "English", genres: ["Horror"], poster: null },
  { title: "It", language: "English", genres: ["Horror"], poster: null },
  { title: "A Quiet Place", language: "English", genres: ["Horror"], poster: null },
  { title: "Get Out", language: "English", genres: ["Horror"], poster: null },
  { title: "The Babadook", language: "English", genres: ["Horror"], poster: null },
  { title: "Insidious", language: "English", genres: ["Horror"], poster: null },
  { title: "Sinister", language: "English", genres: ["Horror"], poster: null },
  { title: "The Witch", language: "English", genres: ["Horror"], poster: null },
  { title: "Paranoid Park", language: "English", genres: ["Horror"], poster: null },
  { title: "Tumbbad", language: "Hindi", genres: ["Horror"], poster: null },
  { title: "1920", language: "Hindi", genres: ["Horror"], poster: null },
  { title: "Raaz", language: "Hindi", genres: ["Horror"], poster: null },
  { title: "Bhoot", language: "Hindi", genres: ["Horror"], poster: null },
  { title: "Ragini MMS", language: "Hindi", genres: ["Horror"], poster: null },
  { title: "Ek Thi Daayan", language: "Hindi", genres: ["Horror"], poster: null },
  { title: "Pari", language: "Hindi", genres: ["Horror"], poster: null },
  { title: "Stree", language: "Hindi", genres: ["Horror"], poster: null },
  { title: "Bulbbul", language: "Hindi", genres: ["Horror"], poster: null },
  { title: "Ghost Stories", language: "Hindi", genres: ["Horror"], poster: null },
  { title: "Arundhati", language: "Telugu", genres: ["Horror"], poster: null },
  { title: "Raju Gari Gadhi", language: "Telugu", genres: ["Horror"], poster: null },
  { title: "Prema Katha Chitram", language: "Telugu", genres: ["Horror"], poster: null },
  { title: "Gruham", language: "Telugu", genres: ["Horror"], poster: null },
  { title: "Anando Brahma", language: "Telugu", genres: ["Horror"], poster: null },
  { title: "Deyyam", language: "Telugu", genres: ["Horror"], poster: null },
  { title: "Jessie", language: "Telugu", genres: ["Horror"], poster: null },
  { title: "Rakshasi", language: "Telugu", genres: ["Horror"], poster: null },
  { title: "Geethanjali", language: "Telugu", genres: ["Horror"], poster: null },
  { title: "Chandramukhi", language: "Telugu", genres: ["Horror"], poster: null },
  { title: "Ezra", language: "Malayalam", genres: ["Horror"], poster: null },
  { title: "Kumari", language: "Malayalam", genres: ["Horror"], poster: null },
  { title: "Bhoothakaalam", language: "Malayalam", genres: ["Horror"], poster: null },
  { title: "Romancham", language: "Malayalam", genres: ["Horror"], poster: null },
  { title: "9", language: "Malayalam", genres: ["Horror"], poster: null },
  { title: "Pizza", language: "Malayalam", genres: ["Horror"], poster: null },
  { title: "Geethanjali", language: "Malayalam", genres: ["Horror"], poster: null },
  { title: "Aneethi Kathaikal", language: "Malayalam", genres: ["Horror"], poster: null },
  { title: "The House Next Door", language: "Malayalam", genres: ["Horror"], poster: null },
  { title: "Chuzhi", language: "Malayalam", genres: ["Horror"], poster: null },
  { title: "Shivaji Surathkal", language: "Kannada", genres: ["Horror"], poster: null },
  { title: "Mane Maratakkide", language: "Kannada", genres: ["Horror"], poster: null },
  { title: "Ranganayaki", language: "Kannada", genres: ["Horror"], poster: null },
  { title: "Kathasangama", language: "Kannada", genres: ["Horror"], poster: null },
  { title: "Namo", language: "Kannada", genres: ["Horror"], poster: null },
  { title: "Dhwaja", language: "Kannada", genres: ["Horror"], poster: null },
  { title: "Jessie", language: "Kannada", genres: ["Horror"], poster: null },
  { title: "Rose", language: "Kannada", genres: ["Horror"], poster: null },
  { title: "6-5=2", language: "Kannada", genres: ["Horror"], poster: null },
  { title: "Kanchana", language: "Kannada", genres: ["Horror"], poster: null },
  { title: "Kanthaswamy", language: "Tamil", genres: ["Fantasy"], poster: null },
  { title: "Puli", language: "Tamil", genres: ["Fantasy"], poster: null },
  { title: "Aayirathil Oruvan", language: "Tamil", genres: ["Fantasy"], poster: null },
  { title: "7aum Arivu", language: "Tamil", genres: ["Fantasy"], poster: null },
  { title: "I", language: "Tamil", genres: ["Fantasy"], poster: null },
  { title: "Maaveeran", language: "Tamil", genres: ["Fantasy"], poster: null },
  { title: "Magamuni", language: "Tamil", genres: ["Fantasy"], poster: null },
  { title: "Kuttram 23", language: "Tamil", genres: ["Fantasy"], poster: null },
  { title: "Anbe Sivam", language: "Tamil", genres: ["Fantasy"], poster: null },
  { title: "Enthiran", language: "Tamil", genres: ["Fantasy"], poster: null },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    language: "English",
    genres: ["Fantasy"],
    poster: null,
  },
  { title: "Harry Potter and the Sorcerer's Stone", language: "English", genres: ["Fantasy"], poster: null },
  { title: "The Hobbit: An Unexpected Journey", language: "English", genres: ["Fantasy"], poster: null },
  {
    title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    language: "English",
    genres: ["Fantasy"],
    poster: null,
  },
  {
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    language: "English",
    genres: ["Fantasy"],
    poster: null,
  },
  { title: "Pan's Labyrinth", language: "English", genres: ["Fantasy"], poster: null },
  { title: "Avatar", language: "English", genres: ["Fantasy"], poster: null },
  { title: "The Shape of Water", language: "English", genres: ["Fantasy"], poster: null },
  { title: "Stardust", language: "English", genres: ["Fantasy"], poster: null },
  { title: "The Princess Bride", language: "English", genres: ["Fantasy"], poster: null },
  { title: "Brahmāstra: Part One – Shiva", language: "Hindi", genres: ["Fantasy"], poster: null },
  { title: "Aladin", language: "Hindi", genres: ["Fantasy"], poster: null },
  { title: "Baahubali: The Beginning", language: "Hindi", genres: ["Fantasy"], poster: null },
  { title: "Drona", language: "Hindi", genres: ["Fantasy"], poster: null },
  { title: "Koi... Mil Gaya", language: "Hindi", genres: ["Fantasy"], poster: null },
  { title: "Paa", language: "Hindi", genres: ["Fantasy"], poster: null },
  { title: "Jajantaram Mamantaram", language: "Hindi", genres: ["Fantasy"], poster: null },
  { title: "Tumbbad", language: "Hindi", genres: ["Fantasy"], poster: null },
  { title: "Bhool Bhulaiyaa", language: "Hindi", genres: ["Fantasy"], poster: null },
  { title: "Ra.One", language: "Hindi", genres: ["Fantasy"], poster: null },
  { title: "Eega", language: "Telugu", genres: ["Fantasy"], poster: null },
  { title: "Magadheera", language: "Telugu", genres: ["Fantasy"], poster: null },
  { title: "Anaganaga O Dheerudu", language: "Telugu", genres: ["Fantasy"], poster: null },
  { title: "Yamadonga", language: "Telugu", genres: ["Fantasy"], poster: null },
  { title: "Baahubali 2: The Conclusion", language: "Telugu", genres: ["Fantasy"], poster: null },
  { title: "Arundhati", language: "Telugu", genres: ["Fantasy"], poster: null },
  { title: "Brahmotsavam", language: "Telugu", genres: ["Fantasy"], poster: null },
  { title: "Nene Raju Nene Mantri", language: "Telugu", genres: ["Fantasy"], poster: null },
  { title: "Awe", language: "Telugu", genres: ["Fantasy"], poster: null },
  { title: "Naa Peru Surya", language: "Telugu", genres: ["Fantasy"], poster: null },
  { title: "Kantharam", language: "Malayalam", genres: ["Fantasy"], poster: null },
  { title: "Minnal Murali", language: "Malayalam", genres: ["Fantasy"], poster: null },
  { title: "Amen", language: "Malayalam", genres: ["Fantasy"], poster: null },
  { title: "Kumari", language: "Malayalam", genres: ["Fantasy"], poster: null },
  { title: "Anandabhadram", language: "Malayalam", genres: ["Fantasy"], poster: null },
  { title: "Padmini", language: "Malayalam", genres: ["Fantasy"], poster: null },
  { title: "Urumi", language: "Malayalam", genres: ["Fantasy"], poster: null },
  { title: "Manichitrathazhu", language: "Malayalam", genres: ["Fantasy"], poster: null },
  { title: "Njan Gandharvan", language: "Malayalam", genres: ["Fantasy"], poster: null },
  { title: "Vismayathumbathu", language: "Malayalam", genres: ["Fantasy"], poster: null },
  { title: "Kantara", language: "Kannada", genres: ["Fantasy"], poster: null },
  { title: "Avane Srimannarayana", language: "Kannada", genres: ["Fantasy"], poster: null },
  { title: "Vikrant Rona", language: "Kannada", genres: ["Fantasy"], poster: null },
  { title: "Nanjundi Kalyana", language: "Kannada", genres: ["Fantasy"], poster: null },
  { title: "Om", language: "Kannada", genres: ["Fantasy"], poster: null },
  { title: "Gandhada Gudi", language: "Kannada", genres: ["Fantasy"], poster: null },
  { title: "Mungaru Male", language: "Kannada", genres: ["Fantasy"], poster: null },
  { title: "Gaalipata", language: "Kannada", genres: ["Fantasy"], poster: null },
  { title: "Chowka", language: "Kannada", genres: ["Fantasy"], poster: null },
  { title: "Kirik Party", language: "Kannada", genres: ["Fantasy"], poster: null },
  { title: "Super Deluxe", language: "Tamil", genres: ["Drama"], poster: null },
  { title: "Asuran", language: "Tamil", genres: ["Drama"], poster: null },
  { title: "Karnan", language: "Tamil", genres: ["Drama"], poster: null },
  { title: "Jai Bhim", language: "Tamil", genres: ["Drama"], poster: null },
  { title: "Pariyerum Perumal", language: "Tamil", genres: ["Drama"], poster: null },
  { title: "Kaala", language: "Tamil", genres: ["Drama"], poster: null },
  { title: "Aruvi", language: "Tamil", genres: ["Drama"], poster: null },
  { title: "To Let", language: "Tamil", genres: ["Drama"], poster: null },
  { title: "96", language: "Tamil", genres: ["Drama"], poster: null },
  { title: "Peranbu", language: "Tamil", genres: ["Drama"], poster: null },
  { title: "The Shawshank Redemption", language: "English", genres: ["Drama"], poster: null },
  { title: "Forrest Gump", language: "English", genres: ["Drama"], poster: null },
  { title: "The Godfather", language: "English", genres: ["Drama"], poster: null },
  { title: "Schindler's List", language: "English", genres: ["Drama"], poster: null },
  { title: "Fight Club", language: "English", genres: ["Drama"], poster: null },
  { title: "Good Will Hunting", language: "English", genres: ["Drama"], poster: null },
  { title: "The Green Mile", language: "English", genres: ["Drama"], poster: null },
  { title: "12 Years a Slave", language: "English", genres: ["Drama"], poster: null },
  { title: "The Pursuit of Happyness", language: "English", genres: ["Drama"], poster: null },
  { title: "A Beautiful Mind", language: "English", genres: ["Drama"], poster: null },
  { title: "Dangal", language: "Hindi", genres: ["Drama"], poster: null },
  { title: "Lagaan", language: "Hindi", genres: ["Drama"], poster: null },
  { title: "Taare Zameen Par", language: "Hindi", genres: ["Drama"], poster: null },
  { title: "3 Idiots", language: "Hindi", genres: ["Drama"], poster: null },
  { title: "Bajrangi Bhaijaan", language: "Hindi", genres: ["Drama"], poster: null },
  { title: "PK", language: "Hindi", genres: ["Drama"], poster: null },
  { title: "Barfi!", language: "Hindi", genres: ["Drama"], poster: null },
  { title: "Queen", language: "Hindi", genres: ["Drama"], poster: null },
  { title: "Swades", language: "Hindi", genres: ["Drama"], poster: null },
  { title: "Dil Chahta Hai", language: "Hindi", genres: ["Drama"], poster: null },
  { title: "Jersey", language: "Telugu", genres: ["Drama"], poster: null },
  { title: "Fidaa", language: "Telugu", genres: ["Drama"], poster: null },
  { title: "Geetha Govindam", language: "Telugu", genres: ["Drama"], poster: null },
  { title: "Mahanati", language: "Telugu", genres: ["Drama"], poster: null },
  { title: "Rangasthalam", language: "Telugu", genres: ["Drama"], poster: null },
  { title: "Nannaku Prematho", language: "Telugu", genres: ["Drama"], poster: null },
  { title: "Srimanthudu", language: "Telugu", genres: ["Drama"], poster: null },
  { title: "Janatha Garage", language: "Telugu", genres: ["Drama"], poster: null },
  { title: "Atharintiki Daaredi", language: "Telugu", genres: ["Drama"], poster: null },
  { title: "Manam", language: "Telugu", genres: ["Drama"], poster: null },
  { title: "Premam", language: "Malayalam", genres: ["Drama"], poster: null },
  { title: "Charlie", language: "Malayalam", genres: ["Drama"], poster: null },
  { title: "Ustad Hotel", language: "Malayalam", genres: ["Drama"], poster: null },
  { title: "Bangalore Days", language: "Malayalam", genres: ["Drama"], poster: null },
  { title: "Kumbalangi Nights", language: "Malayalam", genres: ["Drama"], poster: null },
  { title: "Maheshinte Prathikaaram", language: "Malayalam", genres: ["Drama"], poster: null },
  { title: "Android Kunjappan Version 5.25", language: "Malayalam", genres: ["Drama"], poster: null },
  { title: "Trance", language: "Malayalam", genres: ["Drama"], poster: null },
  { title: "Uyare", language: "Malayalam", genres: ["Drama"], poster: null },
  { title: "Virus", language: "Malayalam", genres: ["Drama"], poster: null },
  { title: "Kirik Party", language: "Kannada", genres: ["Drama"], poster: null },
  { title: "Mungaru Male", language: "Kannada", genres: ["Drama"], poster: null },
  { title: "Gaalipata", language: "Kannada", genres: ["Drama"], poster: null },
  { title: "Chowka", language: "Kannada", genres: ["Drama"], poster: null },
  { title: "Dia", language: "Kannada", genres: ["Drama"], poster: null },
  { title: "Love Mocktail", language: "Kannada", genres: ["Drama"], poster: null },
  { title: "Gentleman", language: "Kannada", genres: ["Drama"], poster: null },
  { title: "Yuvarathnaa", language: "Kannada", genres: ["Drama"], poster: null },
  { title: "Pailwaan", language: "Kannada", genres: ["Drama"], poster: null },
  { title: "Ambi Ning Vayassaytho", language: "Kannada", genres: ["Drama"], poster: null },
  { title: "Boss Engira Bhaskaran", language: "Tamil", genres: ["Comedy"], poster: null },
  { title: "Soodhu Kavvum", language: "Tamil", genres: ["Comedy"], poster: null },
  { title: "Oru Kal Oru Kannadi", language: "Tamil", genres: ["Comedy"], poster: null },
  { title: "Varuthapadatha Valibar Sangam", language: "Tamil", genres: ["Comedy"], poster: null },
  { title: "Remo", language: "Tamil", genres: ["Comedy"], poster: null },
  { title: "Velainu Vandhutta Vellaikaaran", language: "Tamil", genres: ["Comedy"], poster: null },
  { title: "Thamizh Padam", language: "Tamil", genres: ["Comedy"], poster: null },
  { title: "Naanum Rowdy Dhaan", language: "Tamil", genres: ["Comedy"], poster: null },
  { title: "Comali", language: "Tamil", genres: ["Comedy"], poster: null },
  { title: "Oh My Kadavule", language: "Tamil", genres: ["Comedy"], poster: null },
  { title: "The Grand Budapest Hotel", language: "English", genres: ["Comedy"], poster: null },
  { title: "Superbad", language: "English", genres: ["Comedy"], poster: null },
  { title: "The Hangover", language: "English", genres: ["Comedy"], poster: null },
  { title: "Deadpool", language: "English", genres: ["Comedy"], poster: null },
  { title: "Zombieland", language: "English", genres: ["Comedy"], poster: null },
  { title: "In Bruges", language: "English", genres: ["Comedy"], poster: null },
  { title: "Shaun of the Dead", language: "English", genres: ["Comedy"], poster: null },
  { title: "The Nice Guys", language: "English", genres: ["Comedy"], poster: null },
  { title: "21 Jump Street", language: "English", genres: ["Comedy"], poster: null },
  { title: "Pitch Perfect", language: "English", genres: ["Comedy"], poster: null },
  { title: "3 Idiots", language: "Hindi", genres: ["Comedy"], poster: null },
  { title: "Hera Pheri", language: "Hindi", genres: ["Comedy"], poster: null },
  { title: "Golmaal: Fun Unlimited", language: "Hindi", genres: ["Comedy"], poster: null },
  { title: "Dhamaal", language: "Hindi", genres: ["Comedy"], poster: null },
  { title: "Chup Chup Ke", language: "Hindi", genres: ["Comedy"], poster: null },
  { title: "Phir Hera Pheri", language: "Hindi", genres: ["Comedy"], poster: null },
  { title: "Welcome", language: "Hindi", genres: ["Comedy"], poster: null },
  { title: "Housefull", language: "Hindi", genres: ["Comedy"], poster: null },
  { title: "Fukrey", language: "Hindi", genres: ["Comedy"], poster: null },
  { title: "Pyaar Ka Punchnama", language: "Hindi", genres: ["Comedy"], poster: null },
  { title: "Golkonda High School", language: "Telugu", genres: ["Comedy"], poster: null },
  { title: "Express Raja", language: "Telugu", genres: ["Comedy"], poster: null },
  { title: "Jathi Ratnalu", language: "Telugu", genres: ["Comedy"], poster: null },
  { title: "F2: Fun and Frustration", language: "Telugu", genres: ["Comedy"], poster: null },
  { title: "Ekkadiki Pothavu Chinnavada", language: "Telugu", genres: ["Comedy"], poster: null },
  { title: "Nenu Local", language: "Telugu", genres: ["Comedy"], poster: null },
  { title: "Raju Gari Gadhi 2", language: "Telugu", genres: ["Comedy"], poster: null },
  { title: "Chitralahari", language: "Telugu", genres: ["Comedy"], poster: null },
  { title: "Venky Mama", language: "Telugu", genres: ["Comedy"], poster: null },
  { title: "Prati Roju Pandage", language: "Telugu", genres: ["Comedy"], poster: null },
  { title: "Punyalan Agarbattis", language: "Malayalam", genres: ["Comedy"], poster: null },
  { title: "Ohm Shanthi Oshaana", language: "Malayalam", genres: ["Comedy"], poster: null },
  { title: "Action Hero Biju", language: "Malayalam", genres: ["Comedy"], poster: null },
  { title: "Godha", language: "Malayalam", genres: ["Comedy"], poster: null },
  { title: "Njan Prakashan", language: "Malayalam", genres: ["Comedy"], poster: null },
  { title: "Driving Licence", language: "Malayalam", genres: ["Comedy"], poster: null },
  { title: "Jallikattu", language: "Malayalam", genres: ["Comedy"], poster: null },
  { title: "Android Kunjappan Version 5.25", language: "Malayalam", genres: ["Comedy"], poster: null },
  { title: "Kilukkam", language: "Malayalam", genres: ["Comedy"], poster: null },
  { title: "Ramji Rao Speaking", language: "Malayalam", genres: ["Comedy"], poster: null },
  { title: "Anand", language: "Kannada", genres: ["Comedy"], poster: null },
  { title: "Punda Prachanda", language: "Kannada", genres: ["Comedy"], poster: null },
  { title: "Galate Aliyandru", language: "Kannada", genres: ["Comedy"], poster: null },
  { title: "Aithalakkadi", language: "Kannada", genres: ["Comedy"], poster: null },
  { title: "Mr. and Mrs. Ramachari", language: "Kannada", genres: ["Comedy"], poster: null },
  { title: "Rambo", language: "Kannada", genres: ["Comedy"], poster: null },
  { title: "Victory", language: "Kannada", genres: ["Comedy"], poster: null },
  { title: "Googly", language: "Kannada", genres: ["Comedy"], poster: null },
  { title: "Topiwala", language: "Kannada", genres: ["Comedy"], poster: null },
  { title: "Lucky", language: "Kannada", genres: ["Comedy"], poster: null },
]

const API_KEY = "cfa42dd031421ea1a883a9a8d19d46ed"
const BASE_IMAGE_URL = "https://image.tmdb.org/t/p/w500"

async function fetchWithRetry(url, retries = 2, delay = 500) {
  const controller = new AbortController()
  const timeoutId = setTimeout(() => controller.abort(), 10000) // 10-second timeout

  for (let i = 0; i < retries; i++) {
    try {
      const response = await fetch(url, { signal: controller.signal })
      clearTimeout(timeoutId)
      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status}`)
      }
      return response
    } catch (error) {
      clearTimeout(timeoutId)
      if (i === retries - 1) throw error // Last retry
      console.warn(`Retrying fetch (${i + 1}/${retries}) for ${url}: ${error.message}`)
      await new Promise((resolve) => setTimeout(resolve, delay))
    }
  }
}

async function fetchMoviePosters(filteredMovies, updateCallback) {
  const languageCodeMap = {
    Tamil: "ta",
    Telugu: "te",
    Hindi: "hi",
    Malayalam: "ml",
    Kannada: "kn",
    English: "en",
  }

  const fetchPromises = filteredMovies.map(async (movie) => {
    try {
      const languageCode = languageCodeMap[movie.language] || "en"
      console.log(`Fetching poster for ${movie.title} in language ${languageCode}...`)
      const url = `https://api.themoviedb.org/3/search/movie?api_key=${API_KEY}&query=${encodeURIComponent(movie.title)}&language=${languageCode}`
      const response = await fetchWithRetry(url)
      console.log(`Response status for ${movie.title}: ${response.status}`)

      const data = await response.json()

      if (data.results && data.results.length > 0) {
        const matchedMovie = data.results.find((result) => result.original_language === languageCode) || data.results[0]
        const posterPath = matchedMovie.poster_path
        if (posterPath) {
          movie.poster = `${BASE_IMAGE_URL}${posterPath}`
          console.log(`Poster found for ${movie.title}: ${movie.poster}`)
        } else {
          movie.poster = "https://placehold.co/500x750?text=No+Poster"
          console.log(`No poster found for ${movie.title}, using fallback.`)
        }
      } else {
        movie.poster = "https://placehold.co/500x750?text=Movie+Not+Found"
        console.log(`Movie not found for ${movie.title}, using fallback.`)
      }
    } catch (error) {
      console.error(`Error fetching poster for ${movie.title}:`, error.message)
      movie.poster = "https://placehold.co/500x750?text=Error"
    }
    updateCallback(movie.title, movie.poster)
  })

  await Promise.all(fetchPromises)
  return filteredMovies
}

export { movies, fetchMoviePosters }
